"""empty message

Revision ID: 9f73fa802e8b
Revises: 04234e56d40f
Create Date: 2020-07-25 14:50:44.331921

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f73fa802e8b"
down_revision = "04234e56d40f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("material", "name", existing_type=sa.VARCHAR(length=50), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("material", "name", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###
